cls: TorchAgent
action_space:  Box([-1, -1], [+1, +1], dtype=np.float32)
default_action: [0., 0.]
clip: False
policy_module:
  cls: Recurrent
  layer_type: LSTM
  input_size: 8
  hidden_size: 8
  num_layers: 2
  output_size: 2
