cls: TorchAgent
action_space:  Box([0, 0], [+1, +1], dtype=np.float32)
default_action: [1., 0.]
clip: False
policy_module:
  cls: FeedForward
  input_size: 4
  hidden_size: [4, 5]
  output_size: 2
  activation: [GELU, TanH, null]
