env: examples/agents/gym/classic_control/cart_pole/config/feed_forward/env.yml
agent: examples/agents/gym/classic_control/cart_pole/config/feed_forward/agent.yml
n_episodes: 10
max_steps: 1000
verbose: False
render: False
