world:
  env:
    cls: GymWrapper
    locate: mindcraft.envs.gym_wrapper
    gym_id: CartPole-v1  # see https://gymnasium.farama.org/environments/classic_control/
    gym_kwargs:
      render_mode: human
  agent: data/examples/agents/gym/classic_control/cart_pole/models/feed_forward/evolved-agent.yml
  n_episodes: 4
  load_steps: 0
  verbose: True
  render: True
  delay: 0.001
rollout_kwargs:
  verbose: True
