cls: TorchAgent
action_space:  Box([-1, -1], [+1, +1], dtype=np.float32)
default_action: [0., 0.]
clip: False
policy_module:
  cls: FeedForward
  input_size: 8
  hidden_size: [16, ]
  output_size: 2
  activation: [GELU, null]
